<?php
/**
 * @var $item \DaItem\Entity\Item
 */;
 use DaItem\Helper\ItemHelper;?>
<div class="p-3 text-center">
    <h1><?= $item->getName(); ?></h1>
</div>
<div class="row">
    <div class="col-8">
        <h2>Info</h2>
        <hr>
        <?=str_replace("\n", "<br>", $item->getDescription());?>
    </div>
    <div class="col-4" style="padding-left:0;padding-right:0;overflow:hidden;">
        <div class="hero-profile">
            <h4 class="p-2 pb-4"><?= $item->getName(); ?>
                <small class="edit-button">[<a href="<?= $this->url(
                        'items/item-page/edit-item',
                        [
                            'action' => 'edit',
                            'item'   => $item->getAlias(),
                        ]
                    );
                    ?>">edit</a>]</small>
            </h4>
            <img class="avatar" src="<?=$item->getImage();?>">
            <i class="text-center p-2" style="display: block"><?=$item->getLore();?></i>
            <div class="row text-center font-weight-bold" style="margin:0">
                <div class="col-6" style="background-color: #dff124;">
                    Cost<br><?=$item->getPrice();?>
                </div>
                <div class="col-6" style="background-color: #75e276;">
                    Bought from<br>
                    <?=ItemHelper::$categoryMap[$item->getCategory()];?>
                </div>
            </div>
            <h5 class="p-2">Bonuses</h5>
            <?php if($item->getDmgIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getDmgIncrease();?></div>
                    <div class="col text-left font-weight-bold">attack damage</div>
                </div>
            <?php endif;?>
            <?php if($item->getStrIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getStrIncrease();?></div>
                    <div class="col text-left font-weight-bold">strength</div>
                </div>
            <?php endif;?>
            <?php if($item->getAgiIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getAgiIncrease();?></div>
                    <div class="col text-left font-weight-bold">agility</div>
                </div>
            <?php endif;?>
            <?php if($item->getIntIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getIntIncrease();?></div>
                    <div class="col text-left font-weight-bold">intelligence</div>
                </div>
            <?php endif;?>
            <?php if($item->getHpIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getHpIncrease();?></div>
                    <div class="col text-left font-weight-bold">health</div>
                </div>
            <?php endif;?>
            <?php if($item->getMpIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getMpIncrease();?></div>
                    <div class="col text-left font-weight-bold">mana</div>
                </div>
            <?php endif;?>
            <?php if($item->getHpRegenIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getHpRegenIncrease();?></div>
                    <div class="col text-left font-weight-bold">health regen</div>
                </div>
            <?php endif;?>
            <?php if($item->getMpRegenIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getMpRegenIncrease();?></div>
                    <div class="col text-left font-weight-bold">mana regen</div>
                </div>
            <?php endif;?>
            <?php if($item->getArmorIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getArmorIncrease();?></div>
                    <div class="col text-left font-weight-bold">armor</div>
                </div>
            <?php endif;?>
            <?php if($item->getMoveSpeedIncrease()):?>
                <div class="row pt-1 pb-1">
                    <div class="col text-right">+<?=$item->getMoveSpeedIncrease();?></div>
                    <div class="col text-left font-weight-bold">move speed</div>
                </div>
            <?php endif;?>
            <?php if(count($itemBuildsInto) || count($childItems)):?>
                <h5 class="p-2">Recipe</h5>
                <div class="p-2"></div>
                <?php if(count($itemBuildsInto)):?>
                    <div class="row text-center"
                         style="justify-content: space-around; margin: 0;">
                        <?php foreach ($itemBuildsInto as $parentItem):?>
                            <a href="<?= $this->url(
                                'items/item-page',
                                [
                                    'action' => 'singleItem',
                                    'item'   => $parentItem->getAlias()
                                ]
                            );
                            ?>">
                                <img style="width:50px; height: 38px;" src="<?= $parentItem->getImage(); ?>">
                            </a>
                        <?php endforeach;?>
                    </div>
                    <div class="row text-center"
                         style="justify-content: space-around; margin: 0;">
                        <img src="<?=$recipeImgTop;?>">
                    </div>
                <?php endif;?>
                <div class="row text-center"
                     style="justify-content: space-around; margin: 0;">
                    <a href="<?= $this->url(
                        'items/item-page',
                        [
                            'action' => 'singleItem',
                            'item'   => $item->getAlias()
                        ]
                    );
                    ?>">
                        <img style="width:50px; height: 38px;" src="<?= $item->getImage(); ?>">
                    </a>
                </div>
                <?php if(count($childItems)):?>
                    <div class="row text-center"
                         style="justify-content: space-around; margin: 0;">
                        <img src="<?=$recipeImgBottom;?>">
                    </div>
                    <div class="row text-center"
                         style="justify-content: space-around; margin: 0;">
                        <?php foreach ($childItems as $childItem):?>
                            <a href="<?= $this->url(
                                'items/item-page',
                                [
                                    'action' => 'singleItem',
                                    'item'   => $childItem['alias']
                                ]
                            );
                            ?>">
                                <img style="width:50px; height: 38px;" src="<?= $childItem['image']; ?>">
                            </a>
                        <?php endforeach;?>
                        <?php if($item->getIsRecipeRequired()):?>
                            <img style="width:50px; height: 38px;" src="https://liquipedia.net/commons/images/thumb/6/64/Recipe.png/48px-Recipe.png">
                        <?php endif;?>
                    </div>
                <?php endif;?>
                <div class="p-2"></div>
            <?php endif;?>
        </div>
    </div>
</div>
<div class="clearfix mt-5"></div>
