<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet('https://pro.fontawesome.com/releases/v5.10.0/css/all.css')
    ?>

    <!-- Scripts -->
    <?  $this->inlineScript()
        ->prependFile($this->basePath('js/script.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js')
    ?>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark"
     role="navigation">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('heroes') ?>">Heroes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('talents') ?>">Talents</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('items') ?>">Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('neutral-items') ?>">Neutral Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('matches') ?>">Matches</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('hero-builder') ?>">Hero Builder</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Stats
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="<?= $this->url('hero-stats') ?>">Hero Stats</a>
                        <a class="dropdown-item" href="<?= $this->url('item-stats') ?>">Item Stats</a>
                        <a class="dropdown-item" href="<?= $this->url('neutral-item-stats') ?>">Neutral items Stats</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->content ?>
    <footer>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
