<?php
/**
 * @var $hero \DaHero\Entity\Hero
 */; ?>
<div class="p-3 text-center">
    <h1 class="mb-3">Heroes</h1>
    <img src="/img/strength_header.png">
</div>
<?php foreach ($heroes['str'] as $hero): ?>
    <div class="d-inline-block m-2 hero-block">
        <a href="<?= $this->url(
            'heroes/hero-page',
            [
                'action' => 'singleHero',
                'hero'   => $hero->getAlias(),
            ]
        );?>">
            <img src="<?=$hero->getImage();?>">
            <span><?= $hero->getName(); ?></span>
        </a>
    </div>
<?php endforeach; ?>
<div class="p-3 text-center">
    <img src="/img/agility_header.png">
</div>
<?php foreach ($heroes['agi'] as $hero): ?>
    <div class="d-inline-block m-2 hero-block">
        <a href="<?= $this->url(
            'heroes/hero-page',
            [
                'action' => 'singleHero',
                'hero'   => $hero->getAlias(),
            ]
        );?>">
            <img src="<?=$hero->getImage();?>">
            <span><?= $hero->getName(); ?></span>
        </a>
    </div>
<?php endforeach; ?>
<div class="p-3 text-center">
    <img src="/img/intelligence_header.png">
</div>
<?php foreach ($heroes['int'] as $hero): ?>
    <div class="d-inline-block m-2 hero-block">
        <a href="<?= $this->url(
            'heroes/hero-page',
            [
                'action' => 'singleHero',
                'hero'   => $hero->getAlias(),
            ]
        );?>">
            <img src="<?=$hero->getImage();?>">
            <span><?= $hero->getName(); ?></span>
        </a>
    </div>
<?php endforeach; ?>
<?/*php foreach ($heroes as $hero): ?>
    <p>
        <a href="<?= $this->url(
            'heroes/hero-page',
            [
                'action' => 'singleHero',
                'hero'   => strtolower(str_replace(' ', '_', $hero->getName()))
            ]
        );
        ?>
        ">
            <?= $hero->getName(); ?>
        </a>
    </p>
    <div><p><?= str_replace(
                '
', '</p><p>', $hero->getLore()
            ); ?></p></div>
<?php endforeach; */?>
