<?php
/**
 * @var $hero \DaHero\Entity\Hero
 */; ?>
    <div class="p-3 text-center">
        <h1 class="mb-3"><?= $hero->getName(); ?>: Edit ability</h1>
    </div>
    <a href="/">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
        <span>Back to list of heroes</span>
    </a>
<?= $this->form()->openTag($form); ?>
<?php $elements = $form->getElements();
foreach ($elements as $element):?>
    <?php if ($element->getName()!=='isUltimateAbility'):?>
        <div class="form-group">
            <label class="form-label"><?= $element->getLabel(); ?></label>
            <?=$this->formElement($element);?>
            <div class="form-errors text-danger">
                <?= $this->formElementErrors($element); ?>
            </div>
        </div>
    <?php else:?>
        <div class="form-check pb-4">
            <?= $this->formElement($element); ?>
            <label class="form-check-label"><?= $element->getLabel(); ?></label>
        </div>
    <?php endif;?>
<?php endforeach; ?>
<?= $this->form()->closeTag(); ?>